### ISSUE TITLE
Build error: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by damienadermann** [idehub/react-native-google-analytics-bridge#28]
Using react native 0.22.2 and following both the rnpm and manual instructions I get a build error
```
Undefined symbols for architecture x86_64:
  "_NSOverwriteMergePolicy", referenced from:
      +[TAGModel contextWithURL:] in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      -[GAIDataStore contextWithModel:URL:] in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_NSSQLiteErrorDomain", referenced from:
      -[GAIDataStore performBlockAndWait:withError:] in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_NSSQLiteStoreType", referenced from:
      +[TAGModel migrateToCurrentVersion:] in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      +[TAGModel coordinatorWithURL:] in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      -[GAIDataStore coordinatorWithModel:URL:] in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_OBJC_CLASS_$_NSAttributeDescription", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAICoreDataUtil.o)
  "_OBJC_CLASS_$_NSEntityDescription", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGDataProvider.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAICoreDataUtil.o)
  "_OBJC_CLASS_$_NSFetchRequest", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_OBJC_CLASS_$_NSManagedObject", referenced from:
      _OBJC_CLASS_$_TAGHit in libRCTGoogleAnalyticsBridge.a(TAGHit.o)
  "_OBJC_CLASS_$_NSManagedObjectContext", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_OBJC_CLASS_$_NSManagedObjectModel", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAICoreDataUtil.o)
  "_OBJC_CLASS_$_NSMappingModel", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
  "_OBJC_CLASS_$_NSMigrationManager", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
  "_OBJC_CLASS_$_NSPersistentStoreCoordinator", referenced from:
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(TAGModel.o)
      objc-class-ref in libRCTGoogleAnalyticsBridge.a(GAIDataStore.o)
  "_OBJC_METACLASS_$_NSManagedObject", referenced from:
      _OBJC_METACLASS_$_TAGHit in libRCTGoogleAnalyticsBridge.a(TAGHit.o)
  "_deflate", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_deflateEnd", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_deflateInit2_", referenced from:
      +[GAICompressionUtil gai_dataByCompressingBytes:length:compressionLevel:mode:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_inflate", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_inflateEnd", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_inflateInit2_", referenced from:
      +[GAICompressionUtil gai_dataByInflatingBytes:length:isRawData:] in libRCTGoogleAnalyticsBridge.a(GAICompressionUtil.o)
  "_sqlite3_bind_blob", referenced from:
      -[TAGDataLayerPersistentStoreImpl writeEntriesToDatabase:expireTime:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_bind_double", referenced from:
      -[GAIAnalyticsPropertiesStore bindRecord:toUpsertStatement:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
  "_sqlite3_bind_int", referenced from:
      -[TAGDataLayerPersistentStoreImpl deleteEntries:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_bind_int64", referenced from:
      -[GAIAnalyticsPropertiesStore bindRecord:toUpsertStatement:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[TAGDataLayerPersistentStoreImpl writeEntriesToDatabase:expireTime:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl peekEntryIds:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl deleteEntriesOlderThan:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_bind_text", referenced from:
      -[GAISqlStore tableExists:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAIAnalyticsPropertiesStore bindRecord:toUpsertStatement:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore selectStmtWithTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[TAGDataLayerPersistentStoreImpl clearKeysWithPrefixSingleThreaded:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl writeEntriesToDatabase:expireTime:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_close", referenced from:
      -[GAISqlStore closeDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[TAGDataLayerPersistentStoreImpl closeDatabase] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_column_blob", referenced from:
      -[TAGDataLayerPersistentStoreImpl loadSerialized] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_column_bytes", referenced from:
      -[TAGDataLayerPersistentStoreImpl loadSerialized] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_column_count", referenced from:
      -[GAISqlStore openAndValidateDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
  "_sqlite3_column_double", referenced from:
      -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
  "_sqlite3_column_int", referenced from:
      -[GAISqlStore rowCountForTableWithName:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
  "_sqlite3_column_int64", referenced from:
      -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[TAGDataLayerPersistentStoreImpl peekEntryIds:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl numStoredEntries] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_column_text", referenced from:
      -[GAISqlStore openAndValidateDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAIAnalyticsPropertiesStore hasValidPropertyColumns] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[TAGDataLayerPersistentStoreImpl loadSerialized] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_errcode", referenced from:
      -[TAGDataLayerPersistentStoreImpl prepareSql:description:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_errmsg", referenced from:
      -[GAISqlStore errorMessage] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[TAGDataLayerPersistentStoreImpl clearKeysWithPrefixSingleThreaded:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl writeEntriesToDatabase:expireTime:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl deleteEntries:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl numStoredEntries] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl deleteEntriesOlderThan:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      -[TAGDataLayerPersistentStoreImpl tablePresent:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      ...
  "_sqlite3_finalize", referenced from:
      -[GAISqlStore removeStatementForQuery:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore finalizeAndClearStatements] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore openAndValidateDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore prepareSql:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore executeSql:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAIAnalyticsPropertiesStore hasValidPropertyColumns] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[TAGDataLayerPersistentStoreImpl clearKeysWithPrefixSingleThreaded:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
      ...
  "_sqlite3_open", referenced from:
      -[TAGDataLayerPersistentStoreImpl openDatabaseAndInitStatements] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_open_v2", referenced from:
      -[GAISqlStore openAndValidateDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
  "_sqlite3_prepare_v2", referenced from:
      -[GAISqlStore prepareSql:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[TAGDataLayerPersistentStoreImpl prepareSql:description:] in libRCTGoogleAnalyticsBridge.a(TAGDataLayerPersistentStoreImpl.o)
  "_sqlite3_reset", referenced from:
      -[GAISqlStore rowCountForTableWithName:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore tableExists:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore dropTableWithName:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAIAnalyticsPropertiesStore upsertPropertyRecord:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore clearPropertiesTable] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore propertyRecordForTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore selectStmtWithTrackingId:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      ...
  "_sqlite3_step", referenced from:
      -[GAISqlStore rowCountForTableWithName:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore openAndValidateDatabase] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore tableExists:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore dropTableWithName:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAISqlStore executeSql:] in libRCTGoogleAnalyticsBridge.a(GAISqlStore.o)
      -[GAIAnalyticsPropertiesStore upsertPropertyRecord:] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      -[GAIAnalyticsPropertiesStore hasValidPropertyColumns] in libRCTGoogleAnalyticsBridge.a(GAIAnalyticsPropertiesStore.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by damienadermann** [comment]
Issue persists after upgrading to 0.24.1

**Comment by cbrevik** [comment]
Hi @damienadermann! 

Just to get the easy stuff out of the way, when you say "manual instructions", did you do [step 5 from the guide](https://github.com/idehub/react-native-google-analytics-bridge#manual-installation-ios)? That is required even if you use rnpm. 

Also which version of this library are you trying to use?

**Comment by damienadermann** [comment]
Thanks for responding. I forgot to close the issue after I implemented step 5. Thanks for helping out.

**Comment by krzkaczor** [comment]
For me, it looks like adding `libsqlite3.tbd` instead of `libsqlite3.0.tbd` did the trick.

**Comment by Swapnilchavan18** [comment]
following step 5 from installation guide worked for me. Thanks
