### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by markowork** [idehub/react-native-google-analytics-bridge#238]
### Environment

RN: 0.55.0
Platform: Android
Library version: ^5.6.0

### Steps to Reproduce

Trying to build with react-native run-android suddenly does not work

### Expected Behavior

Build to work

### Actual Behavior

Build fails with an error:
Execution failed for task ':react-native-google-analytics-bridge:compileDebugJavaWithJavac'.

Many errors but all are the same thing, one example would be
error: package com.google.android.gms.tagmanager does not exist
import com.google.android.gms.tagmanager.TagManager;

Same for ContainerHolder & DataLayer.
                                        ^
It's like analytics from google play services suddenly stopped working?

Weird thing is I was working on this project whole morning - I go away from keyboard for 5 minutes and now I can't build anymore :/ 

These are my dependencies:

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile project(':react-native-touch-id')
    compile project(':react-native-svg')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-blur')
    compile project(':react-native-splash-screen')
    compile project(':react-native-restart')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-device-info')
    compile 'com.stripe:stripe-android:5.1.0'
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.android.support:support-v4:26.0.1'
    compile 'com.android.support:multidex:1.0.1'
    compile ('com.pulsatehq.sdk:PulsateSdk:2.10.2') {
        exclude group: 'com.google.android.gms'
    }
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.android.gms:play-services-wallet:+'
    compile "com.facebook.react:react-native:+"  // From node_modules
}

compileSdkVersion/targetSdkVersion 26
buildToolsVersion '27.0.3'

Any ideas? Thanks

**Comment by felixus95** [comment]
+1 Really annoying.

**Comment by matr1xprogrammer** [comment]
I'm having the same issue. My build was working previously but it had all sorts of errors today.


> node_modules/react-native-google-analytics-bridge/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridgePackage.java:8: error: package com.google.android.gms.tagmanager does not exist
> import com.google.android.gms.tagmanager.ContainerHolder;

> /node_modules/react-native-google-analytics-bridge/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridgePackage.java:16: error: cannot find symbol
>     public GoogleAnalyticsBridgePackage(ContainerHolder containerHolder, String trackingId) {
> 

compileSdkVersion 26
buildToolsVersion '26.0.2'

**Comment by rhysgoehring** [comment]
Same exact issue as posted by @matr1xprogrammer everything was working fine yesterday.

**Comment by doodlemoonch** [comment]
Same issue, started today also

compileSdkVersion 25
buildToolsVersion "25.0.1"

**Comment by nadirHomeFriend** [comment]
same issue for me , RN 0.44 , dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-analytics:+'
}

**Comment by denisk20** [comment]
This is what happens [when you use](https://github.com/idehub/react-native-google-analytics-bridge/blob/master/android/build.gradle#L3) `+` as a dependency version. This means "just give we the latest version, I don't care what it is". Apparently `com.google.android.gms.tagmanager.TagManager` used to be bundled with `com.google.android.gms:play-services-analytics` until today, when google has released play services `15.0.0`, and this class is not there anymore. Now you need to include it as a separate dependency. Or if you substitute `+` (which now results in `15.0.0`) with `12.0.1` (the previous version) everything works. 
Seriously, don't use `+` as a version number, this is very bad practice... `12.0.+` is ok-ish but plain `+` is not...

**Comment by clintonjrobinson** [comment]
@denisk20 Can confirm this is the case.  Changing the build.gradle in react-native-google-analytics-bridge to use 12.0.1 fixed the build issues for me.    Google just released 15.0.0 of play services. https://developers.google.com/android/guides/releases

'''def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION    = "12.0.1" '''

**Comment by leecrossley** [comment]
You should be able to add `googlePlayServicesVersion=12.0.1` to your `android/gradle.properties` - just confirming now

**Comment by denisk20** [comment]
A workaround from @leecrossley is the easiest one and should be sufficient for most cases, one (very minor) drawback is that it adds `googlePlayServicesVersion` to all subprojects that you have. If you want to only add it to `react-native-google-analytics-bridge` you can do this in `build.gradle`

```
subprojects {
    if(name.equals('react-native-google-analytics-bridge')) {
        project.ext.'googlePlayServicesVersion' = '12.0.1'
    }
}
```

**Comment by cbrevik** [comment]
See https://github.com/idehub/react-native-google-analytics-bridge/issues/207#comment-381114538

Yes, I agree targeting + is bad practice. But, setting a specific version has historically had people running to this repo demanding I upgrade versions because some other lib they use did as well. Consequently there has been a ton of conflicting versions used.

**Comment by Deniscapp** [comment]
I am having the same problem with iOS 🤔

**Comment by sibelius** [comment]
we should move to this https://github.com/react-native-community/react-native-camera/pull/1380

**Comment by MaheshNandam** [comment]
hey @cbrevik, 

Indeed, I got two issues as following,

Error:(13, 40) error: package com.idehub.GoogleAnalyticsBridge does not exist
Error:(44, 17) error: cannot find symbol class GoogleAnalyticsBridgePackage

My main build:

repositories {
        maven { url 'https://maven.google.com' }
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }

repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url 'http://sdk.uxcam.com/android'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }

and tried above solutions, but didn't work out for me, can you please look into it?

**Comment by MaheshNandam** [comment]
Error:Failed to resolve: :react-native-google-analytics-bridge:
<a href="openFile:/Users/mahesh/Desktop/develop/connect-mobile/android/app/build.gradle">Open File</a>


Error:(179, 13) Failed to resolve: :com.android.support:appcompat-v7
<a href="openFile:/Users/mahesh/Desktop/develop/connect-mobile/android/app/build.gradle">Show in File</a>

Couldn't find any proper solution yet, can anyone help me on this?

**Comment by jigaryadav** [comment]
the same error started when I build yesterday suddenly my project is like what the hell, it's worse when you are about to leave and you have no idea what just happened

**Comment by jigaryadav** [comment]
got the solution  just add `googlePlayServicesVersion=11.8.0` in your `android/gradle.properties` worked for me

**Comment by MaheshNandam** [comment]
hey @jigaryadav, 

Can you share which distribution version are you using,
distributionUrl=https\://services.gradle.org/distributions/gradle-4.?-all.zip?

**Comment by jigaryadav** [comment]
@MaheshNandam  you must be using another service rather than react-native-google-analytics-bridge

**Comment by MaheshNandam** [comment]
why @jigaryadav,

I had already implemented this library before and its working fine, after updating distributionUrl to 4.4 then this line fails to upgrade compile 'com.android.support:appcompat-v7:26.0.2' due to this 'app getting crash'.

**Comment by swingywc** [comment]
I have used @leecrossley 's solution to build again and it successfully built into my android device. However, it comes out another error: `Could not invoke GoogleAnalyticsBridge.trackScreenView`. Does anyone meet this error?

**Comment by damathryx** [comment]
`googlePlayServicesVersion=12.0.1` didnt work for me.

**Comment by govindprasadgupta** [comment]
For me, googlePlayServicesVersion=12.0.1 didnt work.

**Comment by Tennen** [comment]
sometimes the gms service lacks common.api classes and the app crashes, sometimes lacks tagmanager classes and the compile crashes..

**Comment by MaheshNandam** [comment]
Indeed, I faced the following issues - #238, #207, gradle issue, Failed resolution of: Lcom/google/android/gms/internal/zzjb, Google Play Services Dependency Issues, DexArchiveMergerException unable to merge dex, android crash, unable-to-merge-dex-after-upgrading-android-studio-3-0.

Finally below steps works for me,

Updated the following:

Android Studio - 3.1.1
classpath 'com.android.tools.build:gradle: - 3.1.1 (project/app/build)
classpath 'com.google.gms:google-services: - 3.1.1 (project/app/build)
distributionUrl=https://services.gradle.org/distributions/gradle-4.4-all.zip (at gradle-wrapper.properties)
compile 'com.android.support:appcompat-v7:27.0.3'
Added the following lines:

googlePlayServicesVersion=12.0.1 (at gradle.properties)

compile 'com.android.support:multidex:1.0.3' ( dependency at android/app/build )

compile 'com.google.android.gms:play-services-analytics:12.0.1' ( dependency at android/app/build )

compile 'com.google.firebase:firebase-messaging:12.0.1' ( dependency at android/app/build )

compile 'com.google.firebase:firebase-core:12.0.1' ( dependency at android/app/build )

before adding the below lines refer

     allprojects {
           repositories {
           //start here
           configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
            if (requested.group == 'com.google.android.gms') {
               details.useVersion '12.0.1'
            }
             if (requested.group == 'com.google.firebase') {
                details.useVersion '12.0.1'
              }
            }
          }
         //end
          jcenter()
               maven {
                url "https://maven.google.com"
               }
            }
        }

Hope this helps, cheers 👍.

**Comment by damathryx** [comment]
I have successfully build by doing this
```
    compile(project(':react-native-google-analytics-bridge')){
        exclude group: 'com.google.android.gms'
    }

    compile ("com.google.android.gms:play-services-analytics:12.0.1") {
        force = true;
    }
```
but crashes on launch with error `Could not invoke GoogleAnalyticsBridge.trackScreenView`

**Comment by damathryx** [comment]
@MaheshNandam  worked for me! Thanks!

**Comment by Tennen** [comment]
@MaheshNandam it seems only your solution works for me.. thank you

**Comment by eleva** [comment]
@MaheshNandam worked for me, also! Thank you

**Comment by MayeuldP** [comment]
It doesn't work for me at all.... It s a big issue !

**Comment by thevolcanomanishere** [comment]
```
buildscript {
    repositories {
        jcenter()
        google()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
            }
        }
        mavenLocal()
        jcenter()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.2'
            }
        }
    }
}

```

**Comment by qingfengming** [comment]
add the flowing code to android/build.gradle work for me .

 allprojects {
           repositories {
           //start here
           configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
            if (requested.group == 'com.google.android.gms') {
               details.useVersion '12.0.1'
            }
             if (requested.group == 'com.google.firebase') {
                details.useVersion '12.0.1'
              }
            }
          }
         //end
          jcenter()
               maven {
                url "https://maven.google.com"
               }
            }
        }

**Comment by nikolaia** [comment]
I'll leave this issue open a while for people too see. A pull request for supporting Play Services 15 would be very welcome. @cbrevik and me have no need for the upgrade right now, and won't be spending our already limited time on it (at least not until we need it in our own apps) 👍

**Comment by karlisl** [comment]
Thank you @qingfengming, much appreciated 💯

**Comment by j8seangel** [comment]
Thanks @MaheshNandam !
It worked for me changing the `appcompat` version to `27.0.2`

**Comment by shardick** [comment]
@MaheshNandam works for me in combination with react-native-onesignal

**Comment by jordanmkoncz** [comment]
I ran into this issue as well, just wanted to give a heads up that if you've been using Google Play Services version 10.0.1 (like I have), you can fix this issue without having to upgrade to using Google Play Services version 12.0.1.

In my `/android/build.gradle` file I added the following:

```
allprojects {
  repositories {
    configurations.all {
      resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.google.android.gms') {
          details.useVersion '10.0.1'
        }
        if (requested.group == 'com.google.firebase') {
          details.useVersion '10.0.1'
        }
      }
    }

    // Other pre-existing configuration for `allprojects.repositories` here.
  }
}

subprojects {
  if(name.equals('react-native-google-analytics-bridge')) {
    project.ext.'googlePlayServicesVersion' = '10.0.1'
  }
}
```

And now my app builds again, and appears to work normally when using the app.

Here's some other configuration snippets that may or may not be relevant to getting this solution working.

In `/android/app/build.gradle`:

```
android {
  compileSdkVersion 26
  buildToolsVersion "26.0.2"

  defaultConfig {
    minSdkVersion 16
    targetSdkVersion 22
  }
}
```

```
dependencies {
    compile(project(':react-native-google-analytics-bridge')){
        exclude group: 'com.google.android.gms'
    }
    compile (project(':react-native-fcm')){
        exclude group: "com.google.firebase"
    }
    compile "com.google.firebase:firebase-core:10.0.1" // This decides your firebase SDK version
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile ('com.android.support:appcompat-v7:26.0.0') {
        exclude group: "com.google.android.gms"
    }
    compile "com.facebook.react:react-native:+"  // From node_modules
    // Base Play Services
    compile ("com.google.android.gms:play-services-base:10.0.1") {
        force = true;
    }
    // Required by react-native-google-analytics-bridge
    compile ("com.google.android.gms:play-services-analytics:10.0.1") {
        force = true;
    }
    // Required by react-native-fcm
    compile ('com.google.firebase:firebase-core:10.0.1') {
        force = true;
    }
    // Required by react-native-fcm
    compile ('com.google.firebase:firebase-messaging:10.0.1') {
        force = true;
    }
}
```

**Comment by maggialejandro** [comment]
If you have to use play services 15+ you will need to add:
```
com.google.android.gms:play-services-tagmanager-v4-impl:15.0.2
```

**Comment by rameshdhas** [comment]
I just changed the order of the repositories in the root level build.gradle.
It was like this before

allprojects {
    repositories {
        
        mavenLocal()
        
        jcenter()
        
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
 
       maven { url 'https://maven.google.com' }
        
        maven { url "https://jitpack.io" }
       	
    }
}

After getting the play services error ,  moved the google maven before the jcenter fixed the issue for me.

allprojects {
    repositories {
        
        mavenLocal()
        
        maven { url 'https://maven.google.com' }
       
       jcenter()
        
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
 
    
        
        maven { url "https://jitpack.io" }
       	
    }
}

**Comment by cbrevik** [comment]
Hi guys, this should be fixed in `6.1.0` without any hacks needed.

See [release notes](https://github.com/idehub/react-native-google-analytics-bridge/releases/tag/v6.1.0) for more info.

Would be great if anyone could could confirm that it works for them using this version. 

**Important**: For those already on less than v6 of this library, there are some breaking changes when upgrading to v6+ (if you use ecommerce or custom dimensions). See [wiki post](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Version-6-breaking-changes) for more details.

**Comment by chenop** [comment]
Following the [Manual installation](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation) worked for me!

**Comment by mazenchami** [comment]
@chenop can you please provide some documentation on how you got it to work?

I currently followed `Manual installation` and builds without any issues on `iOS` but fails on `Android`. The follow error is returned: `Compilation failed; see the compiler error output for details.` -> `Failed to resolve: com.google.android.gms:play-services-gcm:16.0.3` when i try to install it, i get `Could not find dependency "com.google.android.gms:play-services-gcm:16.0.3"` Thoughts?

@cbrevik

**Comment by cbrevik** [comment]
Wiki: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems
Or similar issue: https://github.com/idehub/react-native-google-analytics-bridge/issues/280#issuecomment-420906795

I am locking this thread. For anyone coming here in the future; please search the issues first. This has been answered quite a few times now.
